// <auto-generated />
using HotelLisingAPIV1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelLisingAPIV1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240629141447_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelLisingAPIV1.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pakistan",
                            ShortName = "PK"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United States of America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        });
                });

            modelBuilder.Entity("HotelLisingAPIV1.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Islamabad",
                            CountryId = 1,
                            Name = "Marriot",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Karachi",
                            CountryId = 1,
                            Name = "Hilton",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Lahore",
                            CountryId = 1,
                            Name = "Hyatt",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "New York",
                            CountryId = 2,
                            Name = "Holiday Inn",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 5,
                            Address = "London",
                            CountryId = 3,
                            Name = "Marriot",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelLisingAPIV1.Models.Hotel", b =>
                {
                    b.HasOne("HotelLisingAPIV1.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelLisingAPIV1.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
